In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

import lmpsetup
import hmdsetup

import lmp
import hmd

import numpy as np
import matplotlib.pyplot as plt
import analysis

import scipy.constants as cnt

import shutil
import re
import os
import mdtraj as md
import statsmodels.tsa.stattools
import MDAnalysis.analysis as mda
import scipy
from matplotlib.lines import Line2D
from scipy import ndimage
import fgRPA_ucst as fgu


from style_vars import *
plt.style.use('default')
plt.style.use('style.mplstyle')

hps_lines = [Line2D([0], [0], color='black', ls='--'),
                Line2D([0], [0], color='black')]

wt_d4_lines = [Line2D([0], [0], color=C_W),
                Line2D([0], [0], color=C_4)]

import matplotlib.image as mpimg
import matplotlib.gridspec as gridspec

### PLOTS

### EVERYTHING RAN SEPARATELY

#### D4

In [5]:
# eps fun
find_cri=True
phis_mM = 100
ehs = [0,0]
seqname='CPEB4_D4'


u_wt, wt_sp1, wt_sp2, wt_bi1, wt_bi2 = fgu.fgRPA_ucst(seqname=seqname, find_cri=find_cri, phis_mM=phis_mM,
                                            ehs=ehs, parallel=False, epsfun=True,
                                                      name="d4_eps_fun").run()

Seq: CPEB4_D4 = MGDYGFGVLVQSNTGNKSAFPVRFHPHLQPPHHHQNATPSPAAFINNNTAANGSSAGSAWLFPAPATHNIQDEILGSEKAKSQQQEQQDPLEKQQLSPSPGQEAGILPETEKAKSEENQGDNSSENGNGKEKIRIESPVLTGFDYQEATGLGTSTQPLTSSASSLTGFSNWSAAIAPSSSTIINEDASFFHQGGVPAASANNGALLFQNFPHHVSPGFGGSFSPQIGPLSQHHPHHPHFQHHHSQHQQQRRSPASPHPPPFTHRNAAFNQLPHLANNLNKPPSPWSSYQSPSPTPSSSWSPGGGGYGGWGGSQGRDHRRGLNGGITPLNSISPLKKNFASNHIQLQKYARPSSAFAPKSWMEDSLNRADNIFPFPDRPRTFDMHSLESSLIDIMRAENDTIKGQSSLFPMEDGFLDDGRGDQPLHSGLGSPHCFSHQNGE 
phi_s= 0.0018 r_res = 1 , r_con = 1 , r_sal = 1 , eta = 1 
ehs : 0 0
Critical point found in 6.098341226577759 s
u_cri = 1.8685e+00 T*_cri = 0.5352 , phi_cri = 8.48618959e-03
0.10380364354058269 2.8026983755957344
[1.87       1.875      1.88       1.885      1.89       1.895
 1.9        1.905      1.91       1.915      1.92       1.925
 1.93       1.935      1.94       1.945      1.95       1.95
 2.05380364 2.15760729 2.26141093 2.36521457 2.46901822 2.57282186
 2.6766255  2.78042915 2.88423279]
[[1.00000000e-12 2.88423279e+00]
 [1.0000

In [ ]:
# eps = 80
find_cri=True
phis_mM = 100
ehs = [0,0]
umax=2
seqname='CPEB4_D4'
du = 0.001



u_wt, wt_sp1, wt_sp2, wt_bi1, wt_bi2 = fgu.fgRPA_ucst(seqname=seqname, find_cri=find_cri, phis_mM=phis_mM,
                                            ehs=ehs, umax=umax, parallel=False, du=du, eps0=80,
                                                     name="test_d4_eps80").run()

Seq: CPEB4_D4 = MGDYGFGVLVQSNTGNKSAFPVRFHPHLQPPHHHQNATPSPAAFINNNTAANGSSAGSAWLFPAPATHNIQDEILGSEKAKSQQQEQQDPLEKQQLSPSPGQEAGILPETEKAKSEENQGDNSSENGNGKEKIRIESPVLTGFDYQEATGLGTSTQPLTSSASSLTGFSNWSAAIAPSSSTIINEDASFFHQGGVPAASANNGALLFQNFPHHVSPGFGGSFSPQIGPLSQHHPHHPHFQHHHSQHQQQRRSPASPHPPPFTHRNAAFNQLPHLANNLNKPPSPWSSYQSPSPTPSSSWSPGGGGYGGWGGSQGRDHRRGLNGGITPLNSISPLKKNFASNHIQLQKYARPSSAFAPKSWMEDSLNRADNIFPFPDRPRTFDMHSLESSLIDIMRAENDTIKGQSSLFPMEDGFLDDGRGDQPLHSGLGSPHCFSHQNGE 
phi_s= 0.0018 r_res = 1 , r_con = 1 , r_sal = 1 , eta = 1 
ehs : 0 0
Critical point found in 4.0200254917144775 s
u_cri = 2.4756e-02 T*_cri = 40.3947 , phi_cri = 7.37678337e-03
0.00137531651692753 0.03713354595704333
[0.02489323 0.02503076 0.02516829 0.02530582 0.02544336 0.02558089
 0.02571842 0.02585595 0.02599348 0.02613101 0.02626855 0.02640608
 0.02654361 0.02668114 0.02681867 0.0269562  0.02709374 0.02723127
 0.0273688  0.02750633 0.02750633 0.02888165 0.03025696 0.03163228
 0.0330076  0.03438291 0.03575823 0.03713355 0.03850886]


In [ ]:
dd = np.genfromtxt('/home/adria/perdiux/prod/lammps/final/RPA/fg_ucst/bi_test_d4_eps80.txt')
dd
# plt.plot(dd[:,0], dd[:,1])

In [7]:
# eps = 40
find_cri=True
phis_mM = 100
ehs = [0,0]
umax=2
seqname='CPEB4_D4'
du = 0.001



u_wt, wt_sp1, wt_sp2, wt_bi1, wt_bi2 = fgu.fgRPA_ucst(seqname=seqname, find_cri=find_cri, phis_mM=phis_mM,
                                            ehs=ehs, umax=umax, parallel=False, du=du, eps0=40,
                                                     name="d4_eps40").run()

Seq: CPEB4_D4 = MGDYGFGVLVQSNTGNKSAFPVRFHPHLQPPHHHQNATPSPAAFINNNTAANGSSAGSAWLFPAPATHNIQDEILGSEKAKSQQQEQQDPLEKQQLSPSPGQEAGILPETEKAKSEENQGDNSSENGNGKEKIRIESPVLTGFDYQEATGLGTSTQPLTSSASSLTGFSNWSAAIAPSSSTIINEDASFFHQGGVPAASANNGALLFQNFPHHVSPGFGGSFSPQIGPLSQHHPHHPHFQHHHSQHQQQRRSPASPHPPPFTHRNAAFNQLPHLANNLNKPPSPWSSYQSPSPTPSSSWSPGGGGYGGWGGSQGRDHRRGLNGGITPLNSISPLKKNFASNHIQLQKYARPSSAFAPKSWMEDSLNRADNIFPFPDRPRTFDMHSLESSLIDIMRAENDTIKGQSSLFPMEDGFLDDGRGDQPLHSGLGSPHCFSHQNGE 
phi_s= 0.0018 r_res = 1 , r_con = 1 , r_sal = 1 , eta = 1 
ehs : 0 0
Critical point found in 4.260799407958984 s
u_cri = 4.9511e-02 T*_cri = 20.1974 , phi_cri = 7.37678348e-03
0.0027506330338564547 0.07426709191412428
[0.0496     0.0497     0.0498     0.0499     0.05       0.0501
 0.0502     0.0503     0.0504     0.0505     0.0506     0.0507
 0.0508     0.0509     0.051      0.05375063 0.05650127 0.0592519
 0.06200253 0.06475317 0.0675038  0.07025443 0.07300506 0.0757557 ]
[[2.66897742e-07 7.57556973e-02]
 [5.83166270e-12 7.30050643e-02

In [8]:
# eps = 20
find_cri=True
phis_mM = 100
ehs = [0,0]
umax=2
seqname='CPEB4_D4'
du = 0.001



u_wt, wt_sp1, wt_sp2, wt_bi1, wt_bi2 = fgu.fgRPA_ucst(seqname=seqname, find_cri=find_cri, phis_mM=phis_mM,
                                            ehs=ehs, umax=umax, parallel=False, du=du, eps0=20,
                                                     name="d4_eps20").run()

Seq: CPEB4_D4 = MGDYGFGVLVQSNTGNKSAFPVRFHPHLQPPHHHQNATPSPAAFINNNTAANGSSAGSAWLFPAPATHNIQDEILGSEKAKSQQQEQQDPLEKQQLSPSPGQEAGILPETEKAKSEENQGDNSSENGNGKEKIRIESPVLTGFDYQEATGLGTSTQPLTSSASSLTGFSNWSAAIAPSSSTIINEDASFFHQGGVPAASANNGALLFQNFPHHVSPGFGGSFSPQIGPLSQHHPHHPHFQHHHSQHQQQRRSPASPHPPPFTHRNAAFNQLPHLANNLNKPPSPWSSYQSPSPTPSSSWSPGGGGYGGWGGSQGRDHRRGLNGGITPLNSISPLKKNFASNHIQLQKYARPSSAFAPKSWMEDSLNRADNIFPFPDRPRTFDMHSLESSLIDIMRAENDTIKGQSSLFPMEDGFLDDGRGDQPLHSGLGSPHCFSHQNGE 
phi_s= 0.0018 r_res = 1 , r_con = 1 , r_sal = 1 , eta = 1 
ehs : 0 0
Critical point found in 3.6351089477539062 s
u_cri = 9.9023e-02 T*_cri = 10.0987 , phi_cri = 7.37678373e-03
0.0055012660677139225 0.14853418382827605
[0.0991     0.0992     0.0993     0.0994     0.0995     0.0996
 0.0997     0.0998     0.0999     0.1        0.1001     0.1002
 0.1003     0.1004     0.1005     0.1006     0.1007     0.1008
 0.1009     0.101      0.10650127 0.11200253 0.1175038  0.12300506
 0.12850633 0.1340076  0.13950886 0.14501013 0.15051139]
[[1.012849

In [9]:
# eps = 1
find_cri=True
phis_mM = 100
ehs = [0,0]
umax=2
seqname='CPEB4_D4'
du = 0.001



u_wt, wt_sp1, wt_sp2, wt_bi1, wt_bi2 = fgu.fgRPA_ucst(seqname=seqname, find_cri=find_cri, phis_mM=phis_mM,
                                            ehs=ehs, umax=umax, parallel=False, du=du, epsfun=False,
                                                      name="d4_eps1").run()

Seq: CPEB4_D4 = MGDYGFGVLVQSNTGNKSAFPVRFHPHLQPPHHHQNATPSPAAFINNNTAANGSSAGSAWLFPAPATHNIQDEILGSEKAKSQQQEQQDPLEKQQLSPSPGQEAGILPETEKAKSEENQGDNSSENGNGKEKIRIESPVLTGFDYQEATGLGTSTQPLTSSASSLTGFSNWSAAIAPSSSTIINEDASFFHQGGVPAASANNGALLFQNFPHHVSPGFGGSFSPQIGPLSQHHPHHPHFQHHHSQHQQQRRSPASPHPPPFTHRNAAFNQLPHLANNLNKPPSPWSSYQSPSPTPSSSWSPGGGGYGGWGGSQGRDHRRGLNGGITPLNSISPLKKNFASNHIQLQKYARPSSAFAPKSWMEDSLNRADNIFPFPDRPRTFDMHSLESSLIDIMRAENDTIKGQSSLFPMEDGFLDDGRGDQPLHSGLGSPHCFSHQNGE 
phi_s= 0.0018 r_res = 1 , r_con = 1 , r_sal = 1 , eta = 1 
ehs : 0 0
Critical point found in 3.9542131423950195 s
u_cri = 2.4756e-02 T*_cri = 40.3947 , phi_cri = 7.37678337e-03
0.00137531651692753 0.03713354595704333
[0.0248     0.0249     0.025      0.0251     0.0252     0.0253
 0.0254     0.0255     0.0256     0.0257     0.0258     0.0259
 0.026      0.02737532 0.02875063 0.03012595 0.03150127 0.03287658
 0.0342519  0.03562722 0.03700253 0.03837785]
[[3.20214033e-07 3.83778487e-02]
 [1.67505673e-07 3.70025321e-02]
 [2.42808261e-06 3.5

#### 12D

In [13]:
# eps fun
find_cri=True
phis_mM = 100
ehs = [0,0]
umax=2
seqname='CPEB4_12D'
du = 0.001



u_wt, wt_sp1, wt_sp2, wt_bi1, wt_bi2 = fgu.fgRPA_ucst(seqname=seqname, find_cri=find_cri, phis_mM=phis_mM,
                                            ehs=ehs, umax=umax, parallel=False, du=du, epsfun=True,
                                                      name="d12_eps_fun").run()

Seq: CPEB4_12D = MGDYGFGVLVQSNTGNKDAFPVRFHPHLQPPHHHQNADPDPAAFINNNTAANGSSAGSAWLFPAPATHNIQDEILGSEKAKSQQQEQQDPLEKQQLDPSPGQEAGILPETEKAKSEENQGDNSSENGNGKEKIRIESPVLTGFDYQEATGLGTSTQPLTSSASSLTGFSNWSAAIAPSSSTIINEDASFFHQGGVPAASANNGALLFQNFPHHVSPGFGGSFSPQIGPLSQHHPHHPHFQHHHSQHQQQRRDPADPHPPPFTHRNAAFNQLPHLANNLNKPPSPWSSYQSPSPTPSSSWSPGGGGYGGWGGSQGRDHRRGLNGGIDPLNDIDPLKKNFASNHIQLQKYARPSDAFAPKDWMEDDLNRADNIFPFPDRPRTFDMHSLESSLIDIMRAENDTIKGQSSLFPMEDGFLDDGRGDQPLHSGLGSPHCFSHQNGE 
phi_s= 0.0018 r_res = 1 , r_con = 1 , r_sal = 1 , eta = 1 
ehs : 0 0
Critical point found in 4.557608366012573 s
u_cri = 1.7757e+00 T*_cri = 0.5632 , phi_cri = 4.63292327e-03
0.09864929402937506 2.6635309387931265
[1.7757     1.7758     1.7759     1.776      1.7761     1.7762
 1.7763     1.7764     1.7765     1.7766     1.7767     1.7768
 1.7769     1.777      1.777      1.87564929 1.97429859 2.07294788
 2.17159718 2.27024647 2.36889576 2.46754506 2.56619435 2.66484365]
[[1.00000000e-12 2.66484365e+00]
 [1.00000000e-12 2.56619435e+00]


In [14]:
# eps = 80
find_cri=True
phis_mM = 100
ehs = [0,0]
umax=2
seqname='CPEB4_12D'
du = 0.001



u_wt, wt_sp1, wt_sp2, wt_bi1, wt_bi2 = fgu.fgRPA_ucst(seqname=seqname, find_cri=find_cri, phis_mM=phis_mM,
                                            ehs=ehs, umax=umax, parallel=False, du=du, eps0=80,
                                                     name="d12_eps80").run()

Seq: CPEB4_12D = MGDYGFGVLVQSNTGNKDAFPVRFHPHLQPPHHHQNADPDPAAFINNNTAANGSSAGSAWLFPAPATHNIQDEILGSEKAKSQQQEQQDPLEKQQLDPSPGQEAGILPETEKAKSEENQGDNSSENGNGKEKIRIESPVLTGFDYQEATGLGTSTQPLTSSASSLTGFSNWSAAIAPSSSTIINEDASFFHQGGVPAASANNGALLFQNFPHHVSPGFGGSFSPQIGPLSQHHPHHPHFQHHHSQHQQQRRDPADPHPPPFTHRNAAFNQLPHLANNLNKPPSPWSSYQSPSPTPSSSWSPGGGGYGGWGGSQGRDHRRGLNGGIDPLNDIDPLKKNFASNHIQLQKYARPSDAFAPKDWMEDDLNRADNIFPFPDRPRTFDMHSLESSLIDIMRAENDTIKGQSSLFPMEDGFLDDGRGDQPLHSGLGSPHCFSHQNGE 
phi_s= 0.0018 r_res = 1 , r_con = 1 , r_sal = 1 , eta = 1 
ehs : 0 0
Critical point found in 3.9951610565185547 s
u_cri = 2.3380e-02 T*_cri = 42.7722 , phi_cri = 4.21702083e-03
0.0012988721074776652 0.03506954690189701
[0.0234     0.0235     0.0236     0.0237     0.0238     0.0239
 0.024      0.0241     0.0242     0.0243     0.0244     0.0245
 0.0246     0.0247     0.0248     0.0249     0.025      0.025
 0.02629887 0.02759774 0.02889662 0.03019549 0.03149436 0.03279323
 0.0340921  0.03539098]
[[3.11490953e-07 3.53909769e-02]
 [1.353717

In [15]:
# eps = 40
find_cri=True
phis_mM = 100
ehs = [0,0]
umax=2
seqname='CPEB4_12D'
du = 0.001



u_wt, wt_sp1, wt_sp2, wt_bi1, wt_bi2 = fgu.fgRPA_ucst(seqname=seqname, find_cri=find_cri, phis_mM=phis_mM,
                                            ehs=ehs, umax=umax, parallel=False, du=du, eps0=40,
                                                     name="d12_eps40").run()

Seq: CPEB4_12D = MGDYGFGVLVQSNTGNKDAFPVRFHPHLQPPHHHQNADPDPAAFINNNTAANGSSAGSAWLFPAPATHNIQDEILGSEKAKSQQQEQQDPLEKQQLDPSPGQEAGILPETEKAKSEENQGDNSSENGNGKEKIRIESPVLTGFDYQEATGLGTSTQPLTSSASSLTGFSNWSAAIAPSSSTIINEDASFFHQGGVPAASANNGALLFQNFPHHVSPGFGGSFSPQIGPLSQHHPHHPHFQHHHSQHQQQRRDPADPHPPPFTHRNAAFNQLPHLANNLNKPPSPWSSYQSPSPTPSSSWSPGGGGYGGWGGSQGRDHRRGLNGGIDPLNDIDPLKKNFASNHIQLQKYARPSDAFAPKDWMEDDLNRADNIFPFPDRPRTFDMHSLESSLIDIMRAENDTIKGQSSLFPMEDGFLDDGRGDQPLHSGLGSPHCFSHQNGE 
phi_s= 0.0018 r_res = 1 , r_con = 1 , r_sal = 1 , eta = 1 
ehs : 0 0
Critical point found in 3.7376835346221924 s
u_cri = 4.6759e-02 T*_cri = 21.3861 , phi_cri = 4.21702097e-03
0.0025977442149505703 0.07013909380366543
[0.0468     0.0469     0.047      0.0471     0.0472     0.0473
 0.0474     0.0475     0.0476     0.0477     0.0478     0.0479
 0.048      0.05059774 0.05319549 0.05579323 0.05839098 0.06098872
 0.06358647 0.06618421 0.06878195 0.0713797 ]
[[1.94876682e-08 7.13796979e-02]
 [2.24975956e-06 6.87819537e-02]
 [3.41804677e-07 

In [16]:
# eps = 20
find_cri=True
phis_mM = 100
ehs = [0,0]
umax=2
seqname='CPEB4_12D'
du = 0.001



u_wt, wt_sp1, wt_sp2, wt_bi1, wt_bi2 = fgu.fgRPA_ucst(seqname=seqname, find_cri=find_cri, phis_mM=phis_mM,
                                            ehs=ehs, umax=umax, parallel=False, du=du, eps0=20,
                                                     name="d12_eps20").run()

Seq: CPEB4_12D = MGDYGFGVLVQSNTGNKDAFPVRFHPHLQPPHHHQNADPDPAAFINNNTAANGSSAGSAWLFPAPATHNIQDEILGSEKAKSQQQEQQDPLEKQQLDPSPGQEAGILPETEKAKSEENQGDNSSENGNGKEKIRIESPVLTGFDYQEATGLGTSTQPLTSSASSLTGFSNWSAAIAPSSSTIINEDASFFHQGGVPAASANNGALLFQNFPHHVSPGFGGSFSPQIGPLSQHHPHHPHFQHHHSQHQQQRRDPADPHPPPFTHRNAAFNQLPHLANNLNKPPSPWSSYQSPSPTPSSSWSPGGGGYGGWGGSQGRDHRRGLNGGIDPLNDIDPLKKNFASNHIQLQKYARPSDAFAPKDWMEDDLNRADNIFPFPDRPRTFDMHSLESSLIDIMRAENDTIKGQSSLFPMEDGFLDDGRGDQPLHSGLGSPHCFSHQNGE 
phi_s= 0.0018 r_res = 1 , r_con = 1 , r_sal = 1 , eta = 1 
ehs : 0 0
Critical point found in 4.947333812713623 s
u_cri = 9.3519e-02 T*_cri = 10.6930 , phi_cri = 4.21702104e-03
0.005195488429910675 0.1402781876075884
[0.0936     0.0937     0.0938     0.0939     0.094      0.0941
 0.0942     0.0943     0.0944     0.0945     0.0946     0.0947
 0.0948     0.0949     0.095      0.10019549 0.10539098 0.11058647
 0.11578195 0.12097744 0.12617293 0.13136842 0.13656391 0.1417594 ]
[[1.25205472e-08 1.41759396e-01]
 [1.34465084e-07 1.36563907e-01

In [17]:
# eps = 1
find_cri=True
phis_mM = 100
ehs = [0,0]
umax=2
seqname='CPEB4_12D'
du = 0.001



u_wt, wt_sp1, wt_sp2, wt_bi1, wt_bi2 = fgu.fgRPA_ucst(seqname=seqname, find_cri=find_cri, phis_mM=phis_mM,
                                            ehs=ehs, umax=umax, parallel=False, du=du, epsfun=False,
                                                      name="d12_eps1").run()

Seq: CPEB4_12D = MGDYGFGVLVQSNTGNKDAFPVRFHPHLQPPHHHQNADPDPAAFINNNTAANGSSAGSAWLFPAPATHNIQDEILGSEKAKSQQQEQQDPLEKQQLDPSPGQEAGILPETEKAKSEENQGDNSSENGNGKEKIRIESPVLTGFDYQEATGLGTSTQPLTSSASSLTGFSNWSAAIAPSSSTIINEDASFFHQGGVPAASANNGALLFQNFPHHVSPGFGGSFSPQIGPLSQHHPHHPHFQHHHSQHQQQRRDPADPHPPPFTHRNAAFNQLPHLANNLNKPPSPWSSYQSPSPTPSSSWSPGGGGYGGWGGSQGRDHRRGLNGGIDPLNDIDPLKKNFASNHIQLQKYARPSDAFAPKDWMEDDLNRADNIFPFPDRPRTFDMHSLESSLIDIMRAENDTIKGQSSLFPMEDGFLDDGRGDQPLHSGLGSPHCFSHQNGE 
phi_s= 0.0018 r_res = 1 , r_con = 1 , r_sal = 1 , eta = 1 
ehs : 0 0
Critical point found in 4.038821220397949 s
u_cri = 2.3380e-02 T*_cri = 42.7722 , phi_cri = 4.21702083e-03
0.0012988721074776652 0.03506954690189701
[0.0234     0.0235     0.0236     0.0237     0.0238     0.0239
 0.024      0.0241     0.0242     0.0243     0.0244     0.0245
 0.0246     0.0247     0.0248     0.0249     0.025      0.025
 0.02629887 0.02759774 0.02889662 0.03019549 0.03149436 0.03279323
 0.0340921  0.03539098]
[[3.11490953e-07 3.53909769e-02]
 [1.3537174