In [2]:
import os
import sys
import importlib
import matplotlib.pyplot as plt
if '../utils' not in sys.path:
    sys.path.insert(0,'../utils')
import lmp
import lmpsetup
import analysis
import plotter
import numpy as np
import mdtraj as md
import itertools
import time

importlib.reload(lmp);
importlib.reload(lmpsetup);
importlib.reload(analysis);
importlib.reload(plotter);

tr = md.load('/home/adria/data/prod/lammps/CPEB4x50/1.0ls-100I-80e/atom_traj_0.lammpstrj', top='/home/adria/data/prod/lammps/CPEB4x50/1.0ls-100I-80e/topo.pdb')


In [28]:
nchains = 5
natoms = 448
totatoms = tr.n_atoms
dmaps_by_chain = np.zeros(shape=(nchains, nchains-1, tr.n_frames, natoms, natoms))
ti = time.time()
flat_pairs = list(itertools.product(range(448), range(448)))

for c1 in range(nchains):
    for c2 in range(nchains):
        if c1 != c2:
            pairs = list(itertools.product(range(c1*natoms, (c1+1)*natoms),  range(c2*natoms, (c2+1)*natoms)))
            d = md.compute_distances(tr, pairs)
            d = md.geometry.squareform(d, flat_pairs)
            if c2 > c1:
                dmaps_by_chain[c1, c2-1, :, :, :] = d
            else:
                dmaps_by_chain[c1, c2, :, :, :] = d
print(dmaps_by_chain)

[[[[[0.0112559  0.01091927 0.01072436 ... 0.01501074 0.01521216
     0.01545924]
    [0.01159965 0.0112559  0.01105073 ... 0.01533607 0.01554334
     0.01578933]
    [0.01182721 0.01147468 0.0112559  ... 0.0155246  0.01573865
     0.01598178]
    ...
    [0.00809528 0.00775144 0.0075069  ... 0.0112559  0.01144948
     0.01164186]
    [0.00794826 0.00761832 0.00738911 ... 0.01107448 0.0112559
     0.01144225]
    [0.00791652 0.00759372 0.00736405 ... 0.01090893 0.01108347
     0.0112559 ]]

   [[0.0107994  0.01119771 0.01135332 ... 0.01456295 0.01486467
     0.01519218]
    [0.0103941  0.01079632 0.0109555  ... 0.01423387 0.01453019
     0.01486143]
    [0.01026138 0.01066239 0.01080406 ... 0.01392706 0.0142244
     0.01454842]
    ...
    [0.01103754 0.01137166 0.01145102 ... 0.01385244 0.0142069
     0.0145077 ]
    [0.01119129 0.01152939 0.01159677 ... 0.01386265 0.01421361
     0.01450497]
    [0.0111731  0.01152174 0.01158909 ... 0.01386214 0.01420474
     0.01449364]]

   [[0.0127

In [31]:
print(dmaps_by_chain.min(axis=1).mean(axis=1).mean(axis=0)*10)

[[0.08759337 0.087351   0.08723036 ... 0.09762466 0.09788602 0.09807887]
 [0.08755827 0.08732598 0.08716979 ... 0.09764725 0.09790092 0.09810255]
 [0.08748427 0.08723378 0.08705481 ... 0.09780335 0.0980594  0.09827775]
 ...
 [0.09476223 0.09468515 0.09472717 ... 0.10568739 0.10573567 0.1058469 ]
 [0.09489668 0.09480168 0.09483812 ... 0.10569815 0.10578528 0.10590035]
 [0.09497594 0.09487095 0.09490939 ... 0.10575997 0.10585989 0.10598904]]


In [ ]:
import os
import sys
import importlib
import matplotlib.pyplot as plt
if '../utils' not in sys.path:
    sys.path.insert(0,'../utils')
import lmp
import lmpsetup
import analysis
import plotter
import numpy as np
import mdtraj as md
import itertools
import time

importlib.reload(lmp);
importlib.reload(lmpsetup);
importlib.reload(analysis);
importlib.reload(plotter);

sad = analysis.Analysis(oliba_wd='/home/adria/data/prod/lammps/CPEB4x50/1.0ls-100I-80e/',temper=True)
coms = sad.chain_coms()