In [3]:
%load_ext autoreload
%autoreload 2
import mdtraj as md
import numpy as np
import time
import lmp
import analysis

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
s = lmp.LMP(oliba_wd='/home/adria/data/prod/lammps/MYTEST')
s.temper_reorder()

/home/adria/data/prod/lammps/MYTEST/data.data
> Run Completed at 2.59% for TDP43. Ran 25905000 steps for a total of 5182 frames 
FANCY REORDER
A


KeyboardInterrupt: 

In [ ]:
print(s.rg().mean(axis=1))

In [155]:
r = analysis.Analysis(oliba_wd='/home/adria/data/prod/lammps/TDP-BIG')

/home/adria/data/prod/lammps/TDP-BIG/data.data
> Run Completed at 2.59% for TDP43. Ran 25905000 steps for a total of 5182 frames 
> Taking frames every 2 for a total of 1000 to avoid strong correlations


In [156]:
print(r.rg().mean(axis=1))

[24.93564266 26.33549204 28.36512679 30.43061364 33.63827013 37.95508444
 41.81975328 47.53896513 50.96352227 54.75682547 58.2299643  59.23023999]


In [138]:
s = lmp.LMP(oliba_wd='/home/adria/data/prod/lammps/MYTEST')
rdata = s._data_reorder()
print(s.data[:, :, 3].mean(axis=1))
# print(s.data[:, 0:2, 3])
# print("="*40)
# print(rdata[:, 0:2, 3])

/home/adria/data/prod/lammps/MYTEST/data.data
> Run Completed at 2.59% for TDP43. Ran 25905000 steps for a total of 5182 frames 
[252.80081422 268.72368689 286.89546609 300.66487019 323.59539982
 341.22668805 360.14548821 377.97675585 396.24834487 413.81994001
 432.16923365 445.5497005 ]


In [137]:
s = lmp.LMP(oliba_wd='/home/adria/data/prod/lammps/TDP-BIG')
rdata = s._data_reorder()
print(rdata[:, :, 3].mean(axis=1))
print(s.data[:, 0:2, 3])
print("="*40)
print(rdata[:, 0:2, 3])

/home/adria/data/prod/lammps/TDP-BIG/data.data
> Run Completed at 2.59% for TDP43. Ran 25905000 steps for a total of 5182 frames 
[252.80081422 268.72368689 286.89546609 300.66487019 323.59539982
 341.22668805 360.14548821 377.97675585 396.24834487 413.81994001
 432.16923365 445.5497005 ]
[[250.      263.5201 ]
 [268.      263.80548]
 [286.      292.82623]
 [300.      300.04264]
 [322.      341.46916]
 [340.      319.10568]
 [359.      374.67264]
 [377.      382.40215]
 [395.      412.65927]
 [413.      414.64863]
 [431.      438.33022]
 [450.      438.3838 ]]
[[250.      263.5201 ]
 [268.      263.80548]
 [286.      292.82623]
 [300.      300.04264]
 [322.      341.46916]
 [340.      319.10568]
 [359.      374.67264]
 [377.      382.40215]
 [395.      412.65927]
 [413.      414.64863]
 [431.      438.33022]
 [450.      438.3838 ]]


In [139]:
a = np.arange(4*3*5).reshape(4,5,3)
b = a.copy()
a[:,1,:] = b[np.array([3, 1, 0, 2]),1,:]
print(a)

[[[ 0  1  2]
  [48 49 50]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [ 3  4  5]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [33 34 35]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]


In [128]:
b = np.arange(4*3*5).reshape(4,5,3)
c = b.copy()
for Ti,T in enumerate([3, 1, 0, 2]):
    c[T,1,:] = b[Ti,1,:]
print(c)

[[[ 0  1  2]
  [33 34 35]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [48 49 50]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [ 3  4  5]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]
